---
abstract: 'The Wigoot application'
author:
  - 'Jerome Eteve <jerome.eteve@gmail.com>'
build_requires:
  File::Share: '== 0.03'
  Test::More: '== 1.001011'
  Test::Pod::Coverage: '== 1.08'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WG
requires:
  Class::Load: '== 0.21'
  Config::General: '== 2.52'
  Cwd: '== 3.40'
  DBIx::Class: '== 0.08270'
  Devel::REPL: '== 1.003025'
  File::ShareDir: '== 1.03'
  File::Spec: '== 3.40'
  FindBin: '== 1.51'
  Getopt::Long: '== 2.39'
  Log::Any: '== 0.15'
  Log::Any::Adapter: '== 0.11'
  Log::Any::Adapter::Log4perl: '== 0.06'
  Log::Log4perl: '1.43'
  Moose: '== 2.1205'
version: '0.001'
